# Set the build language to Python
language: python

python: 3.7

# Installation
install:
  - pipenv install -e . --skip-lock
  - pipenv install coveralls --skip-lock

# Run the unit test
script:
  - coverage run -m unittest discover

after_success:
  - coveralls

